"""
export_model.py  —  dump the fitted model to web/model_data.js
===============================================================
The static site (GitHub Pages) cannot fit the model in the browser, but the
prediction math only needs the fitted numbers. This script builds the current
model bundle (same path as the API / CLI, so it reuses the disk cache) and
writes every parameter predict.py / simulate.py / elo.py need into
web/model_data.js as a single `MODEL_DATA` global.

Re-run this whenever you want the site to pick up fresh results:
  python3 export_model.py
"""

from __future__ import annotations

import json
import os

import config
from main import build_current_model

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "web", "model_data.js")


def bundle_to_dict(m, ratings, draw_params) -> dict:
    teams = {}
    for t in m.teams:
        i = m.team_index[t]
        teams[t] = {
            "a": round(float(m.attack[i]), 6),        # attack multiplier
            "d": round(float(m.defence[i]), 6),       # defence multiplier
            "w": round(float(m.weighted_matches.get(t, 0.0)), 3),  # data mass
        }
    return {
        "teams": teams,
        "avg_goals": float(m.avg_goals),
        "home_adv": float(m.home_adv),
        "rho": float(m.rho),
        "goal_scale": float(m.goal_scale),
        "elo": {t: round(float(r), 2) for t, r in ratings.items()},
        "draw_params": [float(draw_params[0]), float(draw_params[1])],
    }


def main():
    data = {
        "config": {
            "max_goals": config.MAX_GOALS,
            "min_matches_for_full_trust": config.MIN_MATCHES_FOR_FULL_TRUST,
            "elo_start": config.ELO_START,
            "elo_home_adv": config.ELO_HOME_ADV,
        },
        "base": bundle_to_dict(*build_current_model(use_xg=False)),
    }
    try:
        data["xg"] = bundle_to_dict(*build_current_model(use_xg=True))
    except Exception as exc:  # xG needs StatsBomb event data; site works without it
        print(f"[export] xG bundle skipped: {exc}")

    with open(OUT, "w") as fh:
        fh.write("// Generated by export_model.py — fitted model parameters "
                 "for the static site.\n")
        fh.write("const MODEL_DATA = ")
        json.dump(data, fh, separators=(",", ":"))
        fh.write(";\n")
    print(f"[export] wrote {OUT} ({os.path.getsize(OUT) / 1024:.0f} KB, "
          f"bundles: {', '.join(k for k in data if k != 'config')})")


if __name__ == "__main__":
    main()
